backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "seo-en"
    label: "SEO (EN)"
    folder: "content/seo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Icon", name: "ico", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Json-Ld", name: "jsonLd", widget: "code", default_language: "json", output_code_only: true}
  - name: "seo-es"
    label: "SEO (ES)"
    folder: "content/seo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: es
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "es"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Icon", name: "ico", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Json-Ld", name: "jsonLd", widget: "code", default_language: "json", output_code_only: true}
  - name: "social"
    label: "Social"
    folder: "content/social"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Position", name: "index", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "footer-en"
    label: "Footer (EN)"
    folder: "content/footer"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Quote", name: "quote", widget: "string", required: false}
  - name: "footer-es"
    label: "Footer (ES)"
    folder: "content/footer"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: es
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Quote", name: "quote", widget: "string", required: false}
  - name: "about-me-en"
    label: "About Me (EN)"
    folder: "content/about-me"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "about-me-es"
    label: "About Me (ES)"
    folder: "content/about-me"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: es
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "es"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "summary-en"
    label: "Summary (EN)"
    folder: "content/summary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "summary-es"
    label: "Summary (ES)"
    folder: "content/summary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: es
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "es"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tech-section-en"
    label: "Tech Section (EN)"
    folder: "content/tech-section"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Footer", name: "footer", widget: "markdown", required: false}
  - name: "tech-section-es"
    label: "Tech Section (ES)"
    folder: "content/tech-section"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: es
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "es"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Footer", name: "footer", widget: "markdown", required: false}
  - name: "technologies"
    label: "Technologies"
    folder: "content/technologies"
    sortable_fields: ['index', 'rating', 'title']
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Rating (scale of 0-10)", name: "rating", widget: "number"}
      - {label: "Position", name: "index", widget: "number"}
      - {label: "Featured Image", name: "image", widget: "image"}
  - name: "projects-en"
    label: "Projects (EN)"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ['index', 'date', 'title']
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Position", name: "index", widget: "number"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects-es"
    label: "Projects (ES)"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ['index', 'date', 'title']
    filter:
      field: language
      value: es
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "es"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Position", name: "index", widget: "number"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
